# Generated by Django 5.0.4 on 2024-06-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employeefromfile_location_shift_employee_contact_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_of_joining',
        ),
    ]
