# Generated by Django 5.0.4 on 2024-06-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_vehicle_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizePaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vehicle_no', models.IntegerField()),
                ('distance', models.FloatField()),
                ('time', models.FloatField()),
                ('path_data', models.JSONField()),
            ],
        ),
    ]
