# Generated by Django 5.0.4 on 2024-06-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_changerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='path_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
