# Generated by Django 5.0.4 on 2024-06-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_vehicle_path_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='path_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
