# Generated by Django 5.0.4 on 2024-06-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_modelcombination_modelwiseemployeeroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcombination',
            name='second_level_algo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
