# Generated by Django 5.0.4 on 2024-06-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_modelcombination_second_level_algo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwiseemployeeroute',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
