# Generated by Django 5.0.4 on 2024-06-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_modelwiseemployeeroute_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelwiseemployeeroute',
            old_name='model_comb_id',
            new_name='model_comb',
        ),
        migrations.RemoveField(
            model_name='modelwiseemployeeroute',
            name='description',
        ),
    ]
