# Generated by Django 5.0.4 on 2024-06-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_modelcombination_no_of_vehicles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwiseemployeeroute',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelwiseemployeeroute',
            name='time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='path_data_drop',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
