# Generated by Django 5.0.4 on 2024-06-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_modelwiseemployeeroute_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelResultVehicleWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_data', models.JSONField(blank=True, null=True)),
                ('model_comb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelcombination')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vehicle')),
            ],
        ),
    ]
