# Generated by Django 5.0.7 on 2024-07-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_modelresultvehiclewise'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcombination',
            name='is_implemented',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
