# Generated by Django 5.0.7 on 2024-07-16 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_modelcombination_is_implemented'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeVehicleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vehicle')),
            ],
        ),
    ]
