# Generated by Django 5.0.7 on 2024-07-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_employeevehiclemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwiseemployeeroute',
            name='URL',
            field=models.TextField(blank=True),
        ),
    ]
